# Generated by Django 5.0.4 on 2024-05-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='acces_token',
            new_name='access_token',
        ),
    ]
